apiVersion : apps/v1
kind: Deployment
metadata:
  name: peeyushkrandomapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peeyushkrandomapp
  template:
    metadata:
      labels:
        app: peeyushkrandomapp 
    spec:
      containers:
        - name: peeyushkrandomapp 
          image: tesapprandom2.azurecr.io/peeyushkrandomapp
          ports:
          - containerPort: 80